- Homelab:
    - Proxmox:
        href: https://192.168.100.200:8006
        description: Hypervisor
        icon: proxmox.png
    - Portainer:
        href: http://192.168.10.119:9000
        description: Docker Management
        icon: portainer.png
    - Grafana:
        href: http://192.168.10.119:3000
        description: Monitoring
        icon: grafana.png
    - Pi-hole:
        href: http://192.168.10.100/admin
        description: DNS Ad Blocker
        icon: pi-hole.png
